// src/js/module/battle/command-panel.jsx
import React from 'react';

export default class CommandPanel extends React.Component {
  constructor(props) {
    super(props);

    this.commandLi = _.clone(this.props.ability);

    this.state = {
      command: {
        id: 'special',
      },
    };
  }

  handleChange(key) {
    this.commandLi.special = _.clone(this.props.special);
    this.commandLi.special.id = 'special';

    this.setState({
      command: this.commandLi[key],
    });

    this.props.onCommand(this.commandLi[key]);
  }

  render() {
    let commandElmArr = [];
    let index = 0;

    Object.keys(this.props.ability).forEach((key) => {
      let command = this.props.ability[key];
      commandElmArr.push(<label className={key} key={index + 1}><input type="radio" ref="command" value={key} checked={this.state.command.id === key} onChange={() => this.handleChange(key)} /> {command.name}</label>);

      index++;
    });

    return (
      <div className="command-panel">
        {commandElmArr}
        <label className="special" key={0}><input type="radio" ref="command" value="special" checked={this.state.command.id === 'special'} onChange={() => this.handleChange('special')} /> {this.props.special.name}</label>
        <div className="desc">{this.props.special.name}: {this.props.special.desc}</div>
      </div>
    );
  }
}

// src/vue/components/module/command-panel.vue
<template lang="pug">
.command-panel
  div(v-for="cmd, key in ability")
    label(
      v-bind:class="key"
    )
      input(
        type="radio"
        v-bind:value="key"
        v-bind:checked="currentKey === key"
        v-on:change="handleChange(key)"
      )
      | {{ cmd.name }}
  .desc
    | {{ ability.special.name }} : {{ ability.special.desc }}
</template>

<script>
import _ from 'lodash';

export default {
  name: 'command-panel',
  props: {
    ability: Object,
    command: Object,
    handleCommand: Function,
  },
  data() {
    return {
    };
  },
  methods: {
    handleChange(key) {
      this.handleCommand(this.ability[key]);
    },
  },
  computed: {
    currentKey() {
      return this.command.id || 'special';
    },
  },
  mounted() {
    this.handleChange('special');
  },
}
</script>

<style lang="scss" scoped>
@import "common";

.command-panel {
  position: absolute;

  left: px(20);
  top: px(520);

  width: px(210);

  font-size: px(10);

  .left {
    position: absolute;
    left: px(0);
    top: px(20);
  }

  .right {
    position: absolute;
    left: px(100);
    top: px(20);
  }

  .down {
    position: absolute;
    left: px(50);
    top: px(40);
  }

  .up {
    position: absolute;
    left: px(50);
    top: px(0);
  }

  .restore {
    position: absolute;
    left: px(50);
    top: px(20);
  }

  .special {
    position: absolute;

    left: 0;
    top: px(60);
  }

  .desc {
    position: absolute;

    left: 0;
    top: px(80);
  }
}
</style>
