// src/js/module/command-history.jsx
import React from 'react';

export default class CommandHistory extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    let commandElmArr = [];

    let attackArr = this.props.attackArr || [];

    attackArr.forEach((attack, index) => {
      commandElmArr.push(
        <div className="attack" key={index}>
          <div className="command">{attack.command.name}: {attack.command.desc || attack.command.func.desc} <i className="fa fa-long-arrow-right" aria-hidden="true"></i> {attack.target.name}</div>
        </div>
      );
    });

    return (
      <div className="command-history">
        <div className="back" onClick={() => this.props.onBack()} style={{display: attackArr.length ? 'block' : 'none'}}><i className="fa fa-undo" aria-hidden="true" style={{cursor: 'pointer'}}></i></div>
        <div className="history">{commandElmArr}</div>
      </div>
    );
  }
}

// src/vue/components/module/command-history.vue
<template lang="pug">
.command-history
  .back(
    v-if="attackArr.length"
    v-on:click="handleBack"
  )
    i.fa.fa-undo(aria-hidden="true")
  .history(v-for="attack in attackArr")
    .attack
      .command
        | {{ attack.command.name }}: {{ attack.command.desc || attack.command.func.desc }}
        i.fa.fa-long-arrow-right(aria-hidden="true")
          | {{ attack.target.name }}
</template>

<script>
export default {
  name: 'command-history',
  props: {
    handleBack: Function,
    attackArr: Array,
  },
  computed: {
  },
}
</script>

<style lang="scss" scoped>
@import "common";

.command-history {
  position: absolute;

  left: px(300);
  top: px(520);

  width: px(300);

  font-size: px(10);

  .fa-undo {
    cursor: pointer;
  }
}
</style>
