// src/vue/components/module/command-index.vue
<template lang="pug">
.command-index
  .command(v-for="chara in characterLi")
    .job
      | {{ chara.job }}
    .desc
      | {{ chara.special.name }}: {{ chara.special.desc || chara.special.func.desc}}</div>
</template>

<script>
import { characterLi } from '@/js/lib/character-list';

export default {
  name: 'command-index',
  props: {
  },
  data() {
    return {
    };
  },
  computed: {
    characterLi() {
      return characterLi;
    }
  },
}
</script>

<style lang="scss" scoped>
@import "common";

.command-index {
  position: absolute;

  left: px(920);
  top: px(0);

  .command {
    + .command {
      margin-top: px(10);
    }
  }

  .job {
    font-weight: bold;
    font-size: px(16);
  }

  .desc {
    font-size: px(10);
  }
}
</style>

// src/js/module/battle/command-index.jsx
import React from 'react';

export default class CommandIndex extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    let commandElmArr = [];

    this.props.characterLi.forEach((chara, index) => {
      commandElmArr.push(
        <div className="command" key={index}>
          <div className="job">{chara.job}</div>
          <div className="desc">{chara.special.name}: {chara.special.desc || chara.special.func.desc}</div>
        </div>
      );
    });

    return (
      <div className="command-index">{commandElmArr}</div>
    );
  }
}
